### ISSUE TITLE
Additional pages Design  

### ISSUE THREAD

**Issue by sifuna2002** [C-I-T-CLUB/CIT_CLUB_OFFICIAL_WEB_APP_-FRONTEND#10]
Some pages in the website has no designs.
Would like designs of the following pages to be made, for uniformity:

✅Registration Page
✅ Events page; events, create event
✅Blog page
✅ Projects page
✅ Find Developer page
✅ Gallery page
✅ Login page

**Comment by paminus-kingori** [comment]
Noted, will work on them over the weekend,

**Comment by pollandonderi** [comment]
sifuna have tasks been assigned yet?

**Comment by paullaster** [comment]
> sifuna have tasks been assigned yet?

Hello @pollandonderi please check the issues well I have signed the tasks to all.
Thank you!
