### ISSUE TITLE
Auth: signup, login

### ISSUE THREAD

**Issue by paullaster** [C-I-T-CLUB/CIT_CLUB_OFFICIAL_WEB_APP_-FRONTEND#11]
Sign up, Login, register for cit club membership views
@cyrillekey @MOGIRE11

**Comment by paullaster** [comment]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/43445963/196036774-16cf94ba-6fbc-442a-b77a-074c6b9996f9.png">

I would request you to modify the above form to have the following features.

`{
    email: {
        type: String,
        required: true,
        trim: true,
        validate: [ isEmail],
        unique: true
    },
    name: {
        type: String,
        required: true,
        trim: true,
        min: 8,
        max: 30,
    },
    phonenumber: {
        type: String,
        required: true,
        trim: true,
        min: 10,
        max: 12,
        unique: true,
    },
    course: {
        type: String,
        min: 2,
        max: 6,
        required: true,
        trim: true,
    },
    programingRating: {
        type: Number,
        required: true,
        min: 1,
        max: 2,
        trim: true
    },
    designRating: {
        type: Number,
        required: true,
        min: 1,
        max: 2,
        trim: true
    },
    fieldOfInterest : {
        type: String,
        required: true,
        trim: true,
        min: null,
        max: null,
    },
    password: {
        type: String,
        required: true,
        trim: true,
        min: 8,
        max: 20,
    },
    additionalInfo: {
        type: String,
        required: false,
        trim: true,
        min: null,
        max: 300
    }`
@Vincent-kipngeno @marjan should provide a list of all the tracks and specialization that the club is currently having to help you include enough list on the **Field of interest** input.


For sign up kindly consider the following:
`{
    email: {
        type: String,
        required: true,
        trim: true,
        validate: [isEmail, "Invalid email address provided"],
        unique: [true, "This email address already exists"],
    },
    username: {
        type: String,
        unique: [true, "This username is already taken"],
        required: true,
        trim: true,
        min: 4,
        max: 10,
    },
    password: {
        type: String,
        required: true,
        trim: true,
    },`
I am already doing validation in the backend but you may also opt to do validation in the front end so that I only focus on catching a few that might pass your validation.

Feel free to discuss anything:

**Comment by msashrafUH** [comment]
Current Tracks:

- Web Dev
- Android Dev
- Data Science /Machine Learning
- UI/UX
- Web3
- Cyber sec
- Game Dev
- Flutter
- IOT
- Cloud

**Comment by Vincent-kipngeno** [comment]
Sorry comment

> Current Tracks:
> 
> * Web Dev
> * Android Dev
> * Data Science /Machine Learning
> * UI/UX
> * Web3
> * Cyber sec
> * Game Dev
> * Flutter
> * IOT
> * Cloud

Sorry I commented with a different account.

**Comment by paullaster** [comment]
thanks a lot
RoboticaVision

**Comment by paullaster** [comment]
> <img alt="image" width="296" src="https://user-images.githubusercontent.com/43445963/196036774-16cf94ba-6fbc-442a-b77a-074c6b9996f9.png">
> 
> I would request you to modify the above form to have the following features.
> 
> `{ email: { type: String, required: true, trim: true, validate: [ isEmail], unique: true }, name: { type: String, required: true, trim: true, min: 8, max: 30, }, phonenumber: { type: String, required: true, trim: true, min: 10, max: 12, unique: true, }, course: { type: String, min: 2, max: 6, required: true, trim: true, }, programingRating: { type: Number, required: true, min: 1, max: 2, trim: true }, designRating: { type: Number, required: true, min: 1, max: 2, trim: true }, fieldOfInterest : { type: String, required: true, trim: true, min: null, max: null, }, password: { type: String, required: true, trim: true, min: 8, max: 20, }, additionalInfo: { type: String, required: false, trim: true, min: null, max: 300 }` @Vincent-kipngeno @marjan should provide a list of all the tracks and specialization that the club is currently having to help you include enough list on the **Field of interest** input.
> 
> For sign up kindly consider the following: `{ email: { type: String, required: true, trim: true, validate: [isEmail, "Invalid email address provided"], unique: [true, "This email address already exists"], }, username: { type: String, unique: [true, "This username is already taken"], required: true, trim: true, min: 4, max: 10, }, password: { type: String, required: true, trim: true, },` I am already doing validation in the backend but you may also opt to do validation in the front end so that I only focus on catching a few that might pass your validation.
> 
> Feel free to discuss anything:

I have a suggestion: now that I am done developing login, sigup and join cit club APIs I want to request the front end guys to change few things:
1. Include another input element for  the join citclub component  that records the status of a member:
 status should be a radio button: active, inactive
2. For fields of interest field, change and use check-box instead of select: One can only select up to four areas.
3. Let all the input field names reamin as they are because I have used the `name` value when creating endpoints
4. Both members and normal account users will login using one login page, I have one dedicated end point to hanlde both distinct users.
5. Login details can either be `email- both normal user and members or username- for normal accounts only`.
6. Add password input field to the join citclub component. they will use this password to login.

Feel free so that we can discuss any unclear things: I am available to test for you the endpoints in your presence so that you may see what response to expect.

thank you!

**Comment by paullaster** [comment]
> @paullaster for the interest fields will they be hard coded in the frontend or is there and enpoint i can query to get the endpoints from the database. I propose adding the fields to the db instead of hard coding. The other suggestions are fine

Nice I love the suggestion. I would go for your suggestion and add the api code immediately. so that api will be available to for use ASAp

**Comment by paullaster** [comment]
> > @paullaster for the interest fields will they be hard coded in the frontend or is there and enpoint i can query to get the endpoints from the database. I propose adding the fields to the db instead of hard coding. The other suggestions are fine
> 
> Nice I love the suggestion. I would go for your suggestion and add the api code immediately. so that api will be available to you for use ASAP.

If you want a demo to see what you'll need to get up running with APIs that you'll be using feel free to let me know so that we are a virtual call and do it ASAP

**Comment by MOGIRE11** [comment]
I'm on it

**Comment by paullaster** [comment]
Great, thanks!
RoboticaVision

**Comment by paullaster** [comment]
Kindly, be liaising with @cyrill so that the development is seamless
RoboticaVision

**Comment by paullaster** [comment]
@cyrillekey, Field of interest api is ready:
Let me know in case of anything.

**Comment by paullaster** [comment]
@cyrillekey  thank you so much. ca we meet in the eveing so that we test out?

**Comment by paullaster** [comment]
I have merged your branch to sub master already

**Comment by paullaster** [comment]
Done!
